PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_MAX_LENGTH = 6

PROJECT_STATUS_OPEN = 'open'
PROJECT_STATUS_CLOSED = 'closed'

PROJECT_STATUS_CHOICES = [
    (PROJECT_STATUS_OPEN, 'Open'),
    (PROJECT_STATUS_CLOSED, 'Closed'),
]