# Generated by Django 5.2.4 on 2026-05-20 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=124, unique=True, verbose_name='Навык'),
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, max_length=256, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='github_url',
            field=models.URLField(blank=True, default='', validators=[django.core.validators.RegexValidator('^$|^https?://github\\.com/', 'Ссылка должна вести на GitHub')], verbose_name='GitHub'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=124, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=12, validators=[django.core.validators.RegexValidator('^(\\+7|8)\\d{10}$', 'Телефон: формат +7XXXXXXXXXX (10 цифр после +7)')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=124, verbose_name='Фамилия'),
        ),
    ]
